server:
  port: 9888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:/app/config-data/
            - file:/app/config-data/{profile}

eureka:
  client:
    service-url:
      defaultZone: http://pf-discovery:9761/eureka/
  instance:
    prefer-ip-address: true
