plugins {
    id 'java'
    id 'org.springframework.boot' version "${springBootVersion}" apply false
    id 'io.spring.dependency-management' version "${springDependencyManagementVersion}" apply false
    id 'com.google.protobuf' version "${protobufPluginVersion}" apply false
}

allprojects {
    group = 'com.personalfinance'
    version = '1.0.0'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'

    java {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.compilerArgs.addAll(['-parameters'])
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }
}

ext {
    springCloudBom = "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
}
