spring:
  application:
    name: api-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:9888
  cloud:
    config:
      # Import cache config to get Redis Sentinel connection info
      name: ${spring.application.name},discovery,cache
      fail-fast: false
