server:
  port: 9888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/configs
            - classpath:/configs/{profile}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9761/eureka/
  instance:
    prefer-ip-address: true
