plugins {
    id 'java-library'
    id 'org.springframework.boot' apply false
    id 'io.spring.dependency-management'
}

dependencyManagement {
    imports {
        mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
    }
}

dependencies {
    api project(':common-base')
    api project(':common-cache')
    api 'org.springframework.boot:spring-boot-starter-security'
    api "io.jsonwebtoken:jjwt-api:${jjwtVersion}"
    api "io.jsonwebtoken:jjwt-impl:${jjwtVersion}"
    api "io.jsonwebtoken:jjwt-jackson:${jjwtVersion}"

    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
